name: First action 
on: workflow_dispatch
jobs: 
  first-job:
    name: My first job
    runs-on: ubuntu-latest
    steps: 
      - name: test
        run: echo "Hello world"
      - name: print good bye
        run: echo "done bye!"
